version: 2
updates:
# Keep everything on the main branch up-to-date.
- package-ecosystem: maven
  directory: /
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /src/main/docker
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
- package-ecosystem: bundler
  directory: /docs
  schedule:
    interval: weekly
# Receive minor and patch updates on latest release branch.
- package-ecosystem: maven
  target-branch: 4.13.x
  directory: /
  schedule:
    interval: daily
  ignore:
  - dependency-name: "*"
    update-types:
    - version-update:semver-major
- package-ecosystem: docker
  target-branch: 4.13.x
  directory: /src/main/docker
  schedule:
    interval: daily
  ignore:
  - dependency-name: "*"
    update-types:
    - version-update:semver-major
