[[releasing-with-the-release-workflow]]
= Releasing with the Release Workflow

This is a basic documentation of how to use the GitHub Action based Release Workflow.

== Motivation

The legacy _release.sh_ has to be run on a developer machine and that seemed limiting, so this effort attempts to replace that with a GitHub action based solution that can be run by anyone with write permissions to this repository.
Additionally, this removes the need and stress of having a dev machine ready with the correct environment to build and publish a new release.

Finally, the criteria for this effort was to keep the current workflow in mind and continue to support the creation of new releases based on the _Default Branch_ that creates a new _Release Branch_ of the state there and then.
However, to also support the creation of new releases on the newly created release branches.

== Creating a new Release

This section will describe the process to release a new version of this repository via the new workflow.

=== From the Default Branch

1. ensure the current state in the _Default Branch_ is ready to be released
2. head over to the *Actions* tab in GitHub
3. Select the "*Release CI*" under the _Workflows_ Section
4. The following UI element will have a button to trigger the CI, once clicked the _Use workflow from_ will appear
+
----
This workflow has a workflow_dispatch event trigger.
----
5. ensure that the *Default Branch* is selected in the branch dropdown
6. (optional) if the version you intend to release differs from the version in the branch you can overwrite it by specifying it in the input variable designated for it
7. finally, once all inputs are checked press the "*Run Workflow*" button
8. sit back and relax, once the build runs through successfully, a new release will be created and all the relevant artifacts will be published.
   Finally, a new release branch will get created based on the current state of the Default Branch.

NOTE: While setting the right versions is also part of the workflow be sure that you set the version to the next correct SNAPSHOT in the _Default Branch_ again (Maybe an improvement to be made down the line to this workflow). However, the release branch versions are already properly handled.

=== From a Release Branch

1. ensure the current state in the given _Release Branch_ is ready to be released
2. head over to the *Actions* tab in GitHub
3. Select the "*Release CI*" under the _Workflows_ Section
4. The following UI element will have a button to trigger the CI, once clicked the _Use workflow from_ will appear
+
----
This workflow has a workflow_dispatch event trigger.
----
5. ensure that the correct *Release Branch* is selected in the branch dropdown
6. (optional) if the version you intend to release differs from the version in the branch you can overwrite it by specifying it in the input variable designated for it
7. finally, once all inputs are checked press the "*Run Workflow*" button
8. sit back and relax, once the build runs through successfully, a new release will be created and all the relevant artifacts will be published.

NOTE: This workflow already sets the proper SNAPSHOT version on the release branch to follow a release.
