CREATE TABLE IF NOT EXISTS "KEV_ASSERTION" (
  "ASSERTER" TEXT NOT NULL
, "VULN_SOURCE" TEXT NOT NULL
, "VULN_ID" TEXT NOT NULL
, "CREATED_AT" TIMESTAMPTZ(3) NOT NULL DEFAULT now()
, "UPDATED_AT" TIMESTAMPTZ(3) NOT NULL DEFAULT now()
, "PUBLISHED_AT" TIMESTAMPTZ(3)
, "REQUIRED_ACTION" TEXT
, "KNOWN_RANSOMWARE" BOOLEAN
, "DESCRIPTION" TEXT
, "RAW" JSONB
, CONSTRAINT "KEV_ASSERTION_PK" PRIMARY KEY ("VULN_ID", "VULN_SOURCE", "ASSERTER")
);
