CREATE INDEX CONCURRENTLY IF NOT EXISTS "COMPONENT_STREEBOG_256_IDX"
    ON "COMPONENT" ("STREEBOG_256")
 WHERE "STREEBOG_256" IS NOT NULL;

CREATE INDEX CONCURRENTLY IF NOT EXISTS "COMPONENT_STREEBOG_512_IDX"
    ON "COMPONENT" ("STREEBOG_512")
 WHERE "STREEBOG_512" IS NOT NULL;
