-- Drop the FKs from DEPENDENCYMETRICS / PROJECTMETRICS to COMPONENT / PROJECT.
-- See ADR 029 for details.
ALTER TABLE "DEPENDENCYMETRICS" DROP CONSTRAINT IF EXISTS "DEPENDENCYMETRICS_COMPONENT_FK";
ALTER TABLE "DEPENDENCYMETRICS" DROP CONSTRAINT IF EXISTS "DEPENDENCYMETRICS_PROJECT_FK";
ALTER TABLE "PROJECTMETRICS" DROP CONSTRAINT IF EXISTS "PROJECTMETRICS_PROJECT_FK";
