CREATE TABLE IF NOT EXISTS "PROJECT_LAST_ANALYSIS" (
  "PROJECT_ID" BIGINT NOT NULL
, "ATTEMPTED_AT" TIMESTAMPTZ NOT NULL DEFAULT 'epoch'
, CONSTRAINT "PROJECT_LAST_ANALYSIS_PK" PRIMARY KEY ("PROJECT_ID")
, CONSTRAINT "PROJECT_LAST_ANALYSIS_PROJECT_FK" FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECT" ("ID") ON DELETE CASCADE
) WITH (
  autovacuum_vacuum_scale_factor = 0.05
, autovacuum_vacuum_threshold = 1000
);

-- squawk-ignore require-concurrent-index-creation
CREATE INDEX IF NOT EXISTS "PROJECT_LAST_ANALYSIS_DUE_IDX"
    ON "PROJECT_LAST_ANALYSIS" ("ATTEMPTED_AT", "PROJECT_ID");

CREATE OR REPLACE FUNCTION project_last_analysis_sync()
  RETURNS TRIGGER
  LANGUAGE plpgsql
AS
$$
  BEGIN
    IF NEW."INACTIVE_SINCE" IS NULL THEN
      INSERT INTO "PROJECT_LAST_ANALYSIS" ("PROJECT_ID")
      VALUES (NEW."ID")
      ON CONFLICT ("PROJECT_ID") DO NOTHING;
    ELSE
      DELETE
        FROM "PROJECT_LAST_ANALYSIS"
       WHERE "PROJECT_ID" = NEW."ID";
    END IF;
    RETURN NEW;
  END;
$$;

CREATE OR REPLACE TRIGGER trigger_project_last_analysis_seed
 AFTER INSERT ON "PROJECT"
   FOR EACH ROW
EXECUTE FUNCTION project_last_analysis_sync();

CREATE OR REPLACE TRIGGER trigger_project_last_analysis_sync
 AFTER UPDATE OF "INACTIVE_SINCE" ON "PROJECT"
   FOR EACH ROW
  WHEN (OLD."INACTIVE_SINCE" IS DISTINCT FROM NEW."INACTIVE_SINCE")
EXECUTE FUNCTION project_last_analysis_sync();
