-- Speed up lookups by PURL and version. See https://github.com/DependencyTrack/dependency-track/issues/5710
CREATE INDEX IF NOT EXISTS "VULNERABLESOFTWARE_FULL_PURL_IDX"
    ON "VULNERABLESOFTWARE" ("PURL_TYPE", "PURL_NAMESPACE", "PURL_NAME", "VERSION")
 WHERE "PURL_TYPE" IS NOT NULL;

-- Now redundant. Leading-prefix subset of VULNERABLESOFTWARE_FULL_PURL_IDX.
DROP INDEX IF EXISTS "VULNERABLESOFTWARE_PURL_TYPE_NS_NAME_IDX";
