INSERT INTO "PROJECT_LAST_ANALYSIS" ("PROJECT_ID", "ATTEMPTED_AT")
SELECT "ID"
     , COALESCE("LAST_VULNERABILITY_ANALYSIS", TIMESTAMPTZ 'epoch')
  FROM "PROJECT"
 WHERE "INACTIVE_SINCE" IS NULL
ON CONFLICT ("PROJECT_ID") DO NOTHING;
