ALTER TABLE "COMPONENT"
  ADD COLUMN IF NOT EXISTS "STREEBOG_256" TEXT
, ADD COLUMN IF NOT EXISTS "STREEBOG_512" TEXT;

-- squawk-ignore require-concurrent-index-creation
CREATE INDEX IF NOT EXISTS "COMPONENT_STREEBOG_256_IDX"
    ON "COMPONENT" ("STREEBOG_256")
 WHERE "STREEBOG_256" IS NOT NULL;

-- squawk-ignore require-concurrent-index-creation
CREATE INDEX IF NOT EXISTS "COMPONENT_STREEBOG_512_IDX"
    ON "COMPONENT" ("STREEBOG_512")
 WHERE "STREEBOG_512" IS NOT NULL;
