CREATE TABLE IF NOT EXISTS "WORKLOAD_IDENTITY_PROVIDER" (
  "NAME" TEXT NOT NULL
, "TYPE" TEXT NOT NULL
, "ISSUER" TEXT NOT NULL
, "AUDIENCE" TEXT NOT NULL
, "JWKS_URL" TEXT
, "JWKS" JSONB
, "SESSION_LIFETIME_SECONDS" INT NOT NULL -- squawk-ignore prefer-bigint-over-int
, "CREATED_AT" TIMESTAMPTZ(3) NOT NULL DEFAULT now()
, "UPDATED_AT" TIMESTAMPTZ(3)
, CONSTRAINT "WORKLOAD_IDENTITY_PROVIDER_PK" PRIMARY KEY ("NAME")
, CONSTRAINT "WORKLOAD_IDENTITY_PROVIDER_TYPE_CHECK" CHECK ("TYPE" IN ('OIDC', 'SPIFFE'))
, CONSTRAINT "WORKLOAD_IDENTITY_PROVIDER_KEY_SOURCE_CHECK" CHECK (("JWKS_URL" IS NULL) != ("JWKS" IS NULL))
, CONSTRAINT "WORKLOAD_IDENTITY_PROVIDER_SESSION_LIFETIME_CHECK" CHECK ("SESSION_LIFETIME_SECONDS" BETWEEN 60 AND 86400)
);

CREATE TABLE IF NOT EXISTS "WORKLOAD_IDENTITY_BINDING" (
  "ID" UUID NOT NULL
, "PROVIDER_NAME" TEXT NOT NULL
, "USER_ID" BIGINT NOT NULL
, "SUBJECT" TEXT NOT NULL
, "CONDITION" TEXT
, "CREATED_AT" TIMESTAMPTZ(3) NOT NULL DEFAULT now()
, "LAST_USED_AT" TIMESTAMPTZ(3)
, CONSTRAINT "WORKLOAD_IDENTITY_BINDING_PK" PRIMARY KEY ("ID")
, CONSTRAINT "WORKLOAD_IDENTITY_BINDING_PROVIDER_FK" FOREIGN KEY ("PROVIDER_NAME") REFERENCES "WORKLOAD_IDENTITY_PROVIDER" ("NAME") ON DELETE CASCADE
, CONSTRAINT "WORKLOAD_IDENTITY_BINDING_USER_FK" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID") ON DELETE CASCADE
);

-- squawk-ignore require-concurrent-index-creation
CREATE INDEX IF NOT EXISTS "WORKLOAD_IDENTITY_BINDING_PROVIDER_NAME_IDX"
    ON "WORKLOAD_IDENTITY_BINDING" ("PROVIDER_NAME");

-- squawk-ignore require-concurrent-index-creation
CREATE INDEX IF NOT EXISTS "WORKLOAD_IDENTITY_BINDING_USER_IDX"
    ON "WORKLOAD_IDENTITY_BINDING" ("USER_ID");
