UPDATE "REPOSITORY" SET "AUTHENTICATIONREQUIRED" = FALSE WHERE "AUTHENTICATIONREQUIRED" IS NULL;
ALTER TABLE "REPOSITORY" ALTER COLUMN "AUTHENTICATIONREQUIRED" SET DEFAULT FALSE;
ALTER TABLE "REPOSITORY" ALTER COLUMN "AUTHENTICATIONREQUIRED" SET NOT NULL;
