CREATE TABLE "PACKAGE_HEALTH_METADATA" (
    "PURL" text NOT NULL,

    "STARS" bigint,
    "FORKS" bigint,
    "CONTRIBUTORS" bigint,
    "COMMIT_FREQUENCY_WEEKLY" real,
    "OPEN_ISSUES" bigint,
    "OPEN_PRS" bigint,
    "LAST_COMMIT" timestamp with time zone,
    "BUS_FACTOR" integer,

    "HAS_README" boolean,
    "HAS_CODE_OF_CONDUCT" boolean,
    "HAS_SECURITY_POLICY" boolean,

    "DEPENDENTS" bigint,
    "FILES" bigint,
    "IS_REPO_ARCHIVED" boolean,

    "SCORECARD_SCORE" real,
    "SCORECARD_REF_VERSION" text,
    "SCORECARD_TIMESTAMP" timestamp with time zone,
    "PROJECT_METADATA_OBSERVED_AT" timestamp with time zone,
    "DEPS_DEV_URL" text,
    "GITHUB_URL" text,

    "AVG_ISSUE_AGE_DAYS" real,

    "LAST_FETCH" timestamp with time zone,
    "STATUS" text NOT NULL,

    CONSTRAINT "PACKAGE_HEALTH_METADATA_PK"
       PRIMARY KEY ("PURL"),

    CONSTRAINT "PACKAGE_HEALTH_METADATA_PACKAGE_METADATA_FK"
       FOREIGN KEY ("PURL")
           REFERENCES "PACKAGE_METADATA" ("PURL")
           ON DELETE CASCADE,

    CONSTRAINT "PACKAGE_HEALTH_METADATA_STATUS_CHECK"
       CHECK ("STATUS" IN (
                           'PROCESSED',
                           'NOT_AVAILABLE'
           )),

    CONSTRAINT "PACKAGE_HEALTH_METADATA_STARS_CHECK"
       CHECK ("STARS" IS NULL OR "STARS" >= 0),

    CONSTRAINT "PACKAGE_HEALTH_METADATA_FORKS_CHECK"
       CHECK ("FORKS" IS NULL OR "FORKS" >= 0),

    CONSTRAINT "PACKAGE_HEALTH_METADATA_CONTRIBUTORS_CHECK"
       CHECK ("CONTRIBUTORS" IS NULL OR "CONTRIBUTORS" >= 0),

    CONSTRAINT "PACKAGE_HEALTH_METADATA_COMMIT_FREQUENCY_CHECK"
       CHECK (
           "COMMIT_FREQUENCY_WEEKLY" IS NULL
               OR "COMMIT_FREQUENCY_WEEKLY" >= 0
           ),

    CONSTRAINT "PACKAGE_HEALTH_METADATA_OPEN_ISSUES_CHECK"
       CHECK ("OPEN_ISSUES" IS NULL OR "OPEN_ISSUES" >= 0),

    CONSTRAINT "PACKAGE_HEALTH_METADATA_OPEN_PRS_CHECK"
       CHECK ("OPEN_PRS" IS NULL OR "OPEN_PRS" >= 0),

    CONSTRAINT "PACKAGE_HEALTH_METADATA_BUS_FACTOR_CHECK"
       CHECK ("BUS_FACTOR" IS NULL OR "BUS_FACTOR" >= 0),

    CONSTRAINT "PACKAGE_HEALTH_METADATA_DEPENDENTS_CHECK"
       CHECK ("DEPENDENTS" IS NULL OR "DEPENDENTS" >= 0),

    CONSTRAINT "PACKAGE_HEALTH_METADATA_FILES_CHECK"
       CHECK ("FILES" IS NULL OR "FILES" >= 0),

    CONSTRAINT "PACKAGE_HEALTH_METADATA_AVG_ISSUE_AGE_CHECK"
       CHECK (
           "AVG_ISSUE_AGE_DAYS" IS NULL
               OR "AVG_ISSUE_AGE_DAYS" >= 0
           )
);

CREATE TABLE "PACKAGE_HEALTH_SCORECARD_CHECK" (
    "PURL" text NOT NULL,
    "CHECK_NAME" text NOT NULL,
    "DESCRIPTION" text,
    "SCORE" real,
    "REASON" text,
    "DETAILS" text[] NOT NULL DEFAULT ARRAY[]::text[],
    "DOCUMENTATION_URL" text,

    CONSTRAINT "PACKAGE_HEALTH_SCORECARD_CHECK_PK"
      PRIMARY KEY ("PURL", "CHECK_NAME"),

    CONSTRAINT "PACKAGE_HEALTH_SCORECARD_CHECK_HEALTH_METADATA_FK"
      FOREIGN KEY ("PURL")
          REFERENCES "PACKAGE_HEALTH_METADATA" ("PURL")
          ON DELETE CASCADE
);
