CREATE TABLE IF NOT EXISTS "PACKAGE_METADATA_RESOLUTION" (
  "PURL" TEXT NOT NULL
, "STATUS" TEXT NOT NULL
, "LAST_ATTEMPTED_AT" TIMESTAMPTZ NOT NULL DEFAULT 'epoch'
, CONSTRAINT "PACKAGE_METADATA_RESOLUTION_PK" PRIMARY KEY ("PURL")
, CONSTRAINT "PACKAGE_METADATA_RESOLUTION_STATUS_CHECK" CHECK ("STATUS" IN ('PENDING', 'RESOLVED', 'NOT_FOUND', 'UNRESOLVABLE'))
) WITH (
  autovacuum_vacuum_scale_factor = 0.05
, autovacuum_vacuum_threshold = 1000
);

INSERT INTO "PACKAGE_METADATA_RESOLUTION" ("PURL", "STATUS", "LAST_ATTEMPTED_AT")
SELECT p."PURL"
     , CASE
         WHEN BOOL_OR(pm."LATEST_VERSION" IS NOT NULL) THEN 'RESOLVED'
         WHEN BOOL_OR(pm."PURL" IS NOT NULL) THEN 'NOT_FOUND'
         ELSE 'PENDING'
       END
     , COALESCE(MAX(pm."RESOLVED_AT"), TIMESTAMPTZ 'epoch')
  -- NB: We deduplicate PURLs *before* joining, because identical PURLs
  -- usually repeat across many components.
  FROM (
    SELECT DISTINCT "PURL"
      FROM "COMPONENT"
     WHERE "PURL" IS NOT NULL
  ) AS p
  LEFT JOIN "PACKAGE_ARTIFACT_METADATA" AS pam
    ON pam."PURL" = p."PURL"
  LEFT JOIN "PACKAGE_METADATA" AS pm
    ON pm."PURL" = pam."PACKAGE_PURL"
 GROUP BY p."PURL"
ON CONFLICT ("PURL") DO NOTHING;
