CREATE INDEX CONCURRENTLY IF NOT EXISTS "PACKAGE_METADATA_RESOLUTION_DUE_IDX"
    ON "PACKAGE_METADATA_RESOLUTION" ("LAST_ATTEMPTED_AT", "PURL")
 WHERE "STATUS" != 'UNRESOLVABLE';

-- The RESOLVED_AT columns no longer drive resolution candidacy (see ADR 033)
-- so the indexes are no longer needed.
-- NB: Removal of these indexes also enables HOT updates on both tables.
DROP INDEX CONCURRENTLY IF EXISTS "PACKAGE_METADATA_RESOLVED_AT_IDX";
DROP INDEX CONCURRENTLY IF EXISTS "PACKAGE_ARTIFACT_METADATA_RESOLVED_AT_IDX";
