---
- name: Create EC2 instance and keypair
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - amazon.aws

  vars:
    aws_region: us-east-1
    instance_type: t3.small
    ami_id: "{{ lookup('aws_ssm', '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64', region=aws_region) }}"
    key_name: YoussefAnsible-keypair
    pem_file: "{{ playbook_dir }}/ansible_key.pem"
    security_group: sg-09091d64701497a2f
    subnet_id: subnet-0b4309b00435bfb03

  tasks:
    - name: Create a keypair
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ aws_region }}"
        state: present
      register: new_keypair

    - name: Save private key for reference
      copy:
        content: "{{ new_keypair.key.private_key }}"
        dest: "{{ pem_file }}"
        mode: '0600'
      when: new_keypair.changed

    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: ansible-youssef-al2023
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        region: "{{ aws_region }}"
        security_group: "{{ security_group }}"
        subnet_id: "{{ subnet_id }}"
        wait: yes
        count: 1
        network:
          assign_public_ip: yes
        iam_instance_profile: "YoussefSSMrole"
      register: ec2

    - name: Save instance IP for GitHub Actions artifact
      copy:
        content: "{{ ec2.instances[0].public_ip_address }}"
        dest: "{{ playbook_dir }}/ec2_ip.txt"
      delegate_to: localhost

    - name: Show new instance IP
      debug:
        msg: "EC2 instance launched with IP {{ ec2.instances[0].public_ip_address }}"

# ---------------------------------------------------------
# Second play: Wait for SSM and run commands
# ---------------------------------------------------------
- name: Configure EC2 via SSM
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    instance_id: "{{ ec2.instances[0].instance_id }}"
    aws_region: us-east-1

  tasks:
    - name: Wait until instance is managed by SSM
      amazon.aws.aws_ssm_facts:
        region: "{{ aws_region }}"
        instance_ids:
          - "{{ instance_id }}"
      register: ssm_status
      retries: 20
      delay: 15
      until: ssm_status.instances | length > 0

    - name: Install curl and write test file via SSM
      ansible.builtin.shell: |
        aws ssm send-command \
          --targets "Key=InstanceIds,Values={{ instance_id }}" \
          --document-name "AWS-RunShellScript" \
          --comment "Install curl and write test file" \
          --parameters 'commands=[
            "sudo yum install -y curl",
            "echo Hello SSM > /home/ec2-user/test_ssm.txt",
            "sudo chown ec2-user:ec2-user /home/ec2-user/test_ssm.txt"
          ]' \
          --region {{ aws_region }}
      args:
        executable: /bin/bash
