---
- name: Create EC2 instance and keypair
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - amazon.aws

  vars:
    aws_region: us-east-1
    instance_type: t3.small
    ami_id: ami-0360c520857e3138f
    key_name: YoussefAnsible-keypair
    pem_file: ~/.ssh/YoussefAnsible-keypair.pem
    security_group: sg-09091d64701497a2f
    subnet_id: subnet-0b4309b00435bfb03

  tasks:
    - name: Create a keypair
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ aws_region }}"
        state: present
      register: new_keypair

    - name: Save private key to ~/.ssh on control machine
      copy:
        content: "{{ new_keypair.key.private_key }}"
        dest: "{{ pem_file }}"
        mode: '0600'
      when: new_keypair.changed

    - name: Save private key for GitHub Actions artifact
      copy:
        content: "{{ new_keypair.key.private_key }}"
        dest: "{{ playbook_dir }}/ansible_key.pem"
        mode: '0600'
      delegate_to: localhost
      when: new_keypair.changed

    - name: Set pem_file fact for later plays
      set_fact:
        pem_file_path: "{{ pem_file }}"

    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: ansible-youssef-amazonlinux
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        region: "{{ aws_region }}"
        security_group: "{{ security_group }}"
        subnet_id: "{{ subnet_id }}"
        wait: yes
        count: 1
        network:
          assign_public_ip: yes
        iam_instance_profile: "YoussefSSMrole"
      register: ec2

    - name: Save instance IP for GitHub Actions artifact
      copy:
        content: "{{ ec2.instances[0].public_ip_address }}"
        dest: "{{ playbook_dir }}/ec2_ip.txt"
      delegate_to: localhost

    - name: Show new instance IP
      debug:
        msg: "EC2 instance launched with IP {{ ec2.instances[0].public_ip_address }}"

- name: Configure new EC2 instance
  hosts: all
  become: yes
  vars:
    ansible_host: "{{ hostvars['localhost'].ec2.instances[0].public_ip_address }}"
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "{{ hostvars['localhost'].pem_file_path }}"
  tasks:
    - name: Update all packages
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: Install dependencies
      ansible.builtin.yum:
        name:
          - curl
          - git
        state: present

    - name: Install Docker
      ansible.builtin.yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      ansible.builtin.shell: |
        curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-$(uname -m) -o /usr/libexec/docker/cli-plugins/docker-compose
        chmod +x /usr/libexec/docker/cli-plugins/docker-compose
      args:
        executable: /bin/bash

    - name: Install SSM agent
      ansible.builtin.shell: |
        yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
        systemctl enable amazon-ssm-agent
        systemctl start amazon-ssm-agent
      args:
        executable: /bin/bash
