---
- name: Create EC2 instance, keypair, and install SSM
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - amazon.aws

  vars:
    aws_region: us-east-1
    instance_type: t3.small
    ami_id: ami-0360c520857e3138f
    key_name: YoussefAnsible-keypair
    pem_file: ~/.ssh/YoussefAnsible-keypair.pem
    security_group: sg-09091d64701497a2f
    subnet_id: subnet-0b4309b00435bfb03
    ssm_user: ubuntu

  tasks:
    - name: Create a keypair
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ aws_region }}"
        state: present
      register: new_keypair

    - name: Save private key to ~/.ssh on control machine
      copy:
        content: "{{ new_keypair.key.private_key }}"
        dest: "{{ pem_file }}"
        mode: '0600'
      when: new_keypair.changed

    - name: Save private key for GitHub Actions artifact
      copy:
        content: "{{ new_keypair.key.private_key }}"
        dest: "{{ playbook_dir }}/ansible_key.pem"
        mode: '0600'
      delegate_to: localhost
      when: new_keypair.changed

    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: ansible-youssef-ubuntu
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        region: "{{ aws_region }}"
        security_group: "{{ security_group }}"
        subnet_id: "{{ subnet_id }}"
        wait: yes
        count: 1
        network:
          assign_public_ip: yes
        iam_instance_profile: "YoussefSSMrole"
      register: ec2

    - name: Save instance IP for GitHub Actions artifact
      copy:
        content: "{{ ec2.instances[0].public_ip_address }}"
        dest: "{{ playbook_dir }}/ec2_ip.txt"
      delegate_to: localhost

    - name: Show new instance IP
      debug:
        msg: "EC2 instance launched with IP {{ ec2.instances[0].public_ip_address }}"

    - name: Wait 20 seconds for SSH to become available
      wait_for:
        host: "{{ ec2.instances[0].public_ip_address }}"
        port: 22
        delay: 20
        timeout: 300
        state: started

    - name: Install curl on the instance
      ansible.builtin.apt:
        name: curl
        state: present
      become: yes
      delegate_to: "{{ ec2.instances[0].public_ip_address }}"
      vars:
        ansible_user: "{{ ssm_user }}"
        ansible_ssh_private_key_file: "{{ pem_file }}"

    - name: Download and install SSM agent
      ansible.builtin.shell: |
        curl "https://s3.us-east-1.amazonaws.com/amazon-ssm-us-east-1/latest/debian_amd64/amazon-ssm-agent.deb" -o "amazon-ssm-agent.deb"
        sudo dpkg -i amazon-ssm-agent.deb
        sudo systemctl enable amazon-ssm-agent
        sudo systemctl start amazon-ssm-agent
      become: yes
      args:
        executable: /bin/bash
      delegate_to: "{{ ec2.instances[0].public_ip_address }}"
      vars:
        ansible_user: "{{ ssm_user }}"
        ansible_ssh_private_key_file: "{{ pem_file }}"
