alpine.build-info.application.name=Unknown Alpine Application
alpine.build-info.application.version=0.0.0
alpine.build-info.application.timestamp=1970-01-01 00:00:00
alpine.build-info.application.uuid=00000000-0000-0000-0000-000000000000

dt.api.key.prefix=alpine_
dt.bcrypt.rounds=14
dt.cors.allow.credentials=true
dt.cors.allow.headers=Origin,Content-Type,Authorization,X-Requested-With,Content-Length,Accept,Origin,X-Api-Key,X-Total-Count,*
dt.cors.allow.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
dt.cors.allow.origin=*
dt.cors.enabled=true
dt.cors.expose.headers=Origin,Content-Type,Authorization,X-Requested-With,Content-Length,Accept,Origin,X-Api-Key,X-Total-Count
dt.cors.max.age=3600
dt.data.directory=~/.alpine
dt.database.password=
dt.database.url=jdbc:h2:mem:alpine
dt.database.username=sa
dt.http.timeout.connection=30
dt.http.timeout.pool=60
dt.http.timeout.socket=30
dt.ldap.attribute.mail=mail
dt.ldap.attribute.name=userPrincipalName
dt.ldap.enabled=false
dt.ldap.team.synchronization=false
dt.ldap.user.provisioning=false
dt.oidc.auth.customizer=alpine.server.auth.DefaultOidcAuthenticationCustomizer
dt.oidc.enabled=false
dt.oidc.team.synchronization=false
dt.oidc.teams.claim=groups
dt.oidc.user.provisioning=false
dt.oidc.username.claim=sub
