dt.bcrypt.rounds=4
dt.datasource.password=dtrack
dt.datasource.url=jdbc:postgresql://localhost:5432/dtrack
dt.datasource.username=dtrack
dt.metrics.enabled=true
dt.notification-publisher.email.allow-local-connections=true
dt.notification-publisher.kafka.allow-local-connections=true
dt.secret-management.database.kek=Ccbo1y2QTKVHZbANVb/ER5yvTn5yZe5UtIpZ+eRSnTg=
dt.telemetry.submission.default-enabled=false