/*
 * This file is part of Dependency-Track.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 * Copyright (c) OWASP Foundation. All Rights Reserved.
 */
package org.dependencytrack.upgrade.v4140;

import alpine.common.logging.Logger;
import alpine.common.util.VersionComparator;
import alpine.persistence.AlpineQueryManager;
import alpine.server.upgrade.AbstractUpgradeItem;
import alpine.server.upgrade.UpgradeMetaProcessor;
import alpine.server.util.DbUtil;
import org.dependencytrack.model.ConfigPropertyConstants;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class v4140_1Updater extends AbstractUpgradeItem {

    private static final Logger LOGGER = Logger.getLogger(v4140_1Updater.class);

    @Override
    public String getSchemaVersion() {
        return "4.14.0";
    }

    @Override
    public boolean shouldUpgrade(final AlpineQueryManager qm, final Connection connection) {
        final UpgradeMetaProcessor upgradeMetaProcessor = new UpgradeMetaProcessor(connection);
        final boolean didThisUpgradeRun;
        final boolean didBaseUpgradeRun;
        final boolean migrationStateIncomplete;
        try {
            didThisUpgradeRun = upgradeMetaProcessor.hasUpgradeRan(v4140_1Updater.class);
            didBaseUpgradeRun = upgradeMetaProcessor.hasUpgradeRan(v4140Updater.class);
            migrationStateIncomplete = isMigrationStateIncomplete(connection);
        } catch (SQLException e) {
            throw new IllegalStateException("Failed to check whether %s ran before".formatted(v4140Updater.class), e);
        }
        if (didThisUpgradeRun) {
            return false;
        }
        if (migrationStateIncomplete) {
            return true;
        }

        final VersionComparator currentVersion = upgradeMetaProcessor.getSchemaVersion();
        if (currentVersion == null) {
            return false;
        }

        final VersionComparator version = new VersionComparator(this.getSchemaVersion());
        return version.isNewerThan(currentVersion)
                || (version.equals(currentVersion) && didBaseUpgradeRun);
    }

    @Override
    public void executeUpgrade(final AlpineQueryManager qm, final Connection connection) throws Exception {
        createVulnerabilitySequenceV2Table(connection);
        addConfigProperties(connection);
    }

    private void createVulnerabilitySequenceV2Table(final Connection connection) throws Exception {
        if (tableExists(connection, "VULNERABILITY_SEQUENCE_V2")) {
            LOGGER.debug("VULNERABILITY_SEQUENCE_V2 table already exists, skipping creation");
            return;
        }

        LOGGER.info("Creating VULNERABILITY_SEQUENCE_V2 table");
        final String dbProductName = connection.getMetaData().getDatabaseProductName().toLowerCase();
        final boolean isSqlServer = dbProductName.contains("sql server") || dbProductName.contains("microsoft");

        final String createTableSql = isSqlServer
                ? """
                CREATE TABLE "VULNERABILITY_SEQUENCE_V2" (
                    "ID" BIGINT IDENTITY(1,1) NOT NULL,
                    "ORG_CODE" VARCHAR(64) NOT NULL,
                    "PROJECT_KEY" VARCHAR(128) NOT NULL,
                    "CURRENT_SEQUENCE" BIGINT NOT NULL DEFAULT 0,
                    "LAST_RESET_DATE" DATETIME,
                    "RESET_POLICY" VARCHAR(32) NOT NULL,
                    "CREATED_AT" DATETIME DEFAULT GETDATE(),
                    PRIMARY KEY ("ID"),
                    CONSTRAINT "VULNSEQV2_ORG_PROJECT_IDX" UNIQUE ("ORG_CODE", "PROJECT_KEY")
                )
                """
                : """
                CREATE TABLE "VULNERABILITY_SEQUENCE_V2" (
                    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
                    "ORG_CODE" VARCHAR(64) NOT NULL,
                    "PROJECT_KEY" VARCHAR(128) NOT NULL,
                    "CURRENT_SEQUENCE" BIGINT NOT NULL DEFAULT 0,
                    "LAST_RESET_DATE" TIMESTAMP,
                    "RESET_POLICY" VARCHAR(32) NOT NULL,
                    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY ("ID"),
                    CONSTRAINT "VULNSEQV2_ORG_PROJECT_IDX" UNIQUE ("ORG_CODE", "PROJECT_KEY")
                )
                """;
        DbUtil.executeUpdate(connection, createTableSql);

        DbUtil.executeUpdate(connection, """
                CREATE INDEX "VULNSEQV2_ORG_IDX" ON "VULNERABILITY_SEQUENCE_V2" ("ORG_CODE")
                """);
        DbUtil.executeUpdate(connection, """
                CREATE INDEX "VULNSEQV2_PROJECT_IDX" ON "VULNERABILITY_SEQUENCE_V2" ("PROJECT_KEY")
                """);
    }

    private void addConfigProperties(final Connection connection) throws SQLException {
        createConfigPropertyIfAbsent(connection, ConfigPropertyConstants.VULNERABILITY_ID_ORG_CODE);
        createConfigPropertyIfAbsent(connection, ConfigPropertyConstants.VULNERABILITY_ID_PROJECT_CODE);
        createConfigPropertyIfAbsent(connection, ConfigPropertyConstants.VULNERABILITY_ID_TEMPLATE);
        createConfigPropertyIfAbsent(connection, ConfigPropertyConstants.VULNERABILITY_ID_RESET_POLICY);
        createConfigPropertyIfAbsent(connection, ConfigPropertyConstants.VULNERABILITY_ID_SEQUENCE_PADDING);
    }

    private void createConfigPropertyIfAbsent(final Connection connection, final ConfigPropertyConstants property) throws SQLException {
        if (configPropertyExists(connection, property.getGroupName(), property.getPropertyName())) {
            LOGGER.debug("ConfigProperty already exists, skipping: " + property.name());
            return;
        }

        try (PreparedStatement ps = connection.prepareStatement("""
                INSERT INTO "CONFIGPROPERTY" (
                  "DESCRIPTION"
                , "GROUPNAME"
                , "PROPERTYNAME"
                , "PROPERTYTYPE"
                , "PROPERTYVALUE"
                ) VALUES (?, ?, ?, ?, ?)
                """)) {
            ps.setString(1, property.getDescription());
            ps.setString(2, property.getGroupName());
            ps.setString(3, property.getPropertyName());
            ps.setString(4, property.getPropertyType().name());
            ps.setString(5, property.getDefaultPropertyValue());
            ps.executeUpdate();
        }
    }

    private boolean configPropertyExists(final Connection connection, final String groupName, final String propertyName)
            throws SQLException {
        try (PreparedStatement ps = connection.prepareStatement("""
                SELECT 1
                  FROM "CONFIGPROPERTY"
                 WHERE "GROUPNAME" = ?
                   AND "PROPERTYNAME" = ?
                """)) {
            ps.setString(1, groupName);
            ps.setString(2, propertyName);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next();
            }
        }
    }

    private boolean tableExists(final Connection connection, final String tableName) throws SQLException {
        final DatabaseMetaData metaData = connection.getMetaData();
        try (ResultSet rs = metaData.getTables(null, null, tableName, new String[]{"TABLE"})) {
            return rs.next();
        }
    }

    private boolean isMigrationStateIncomplete(final Connection connection) throws SQLException {
        if (!tableExists(connection, "VULNERABILITY_SEQUENCE_V2")) {
            return true;
        }
        return !configPropertyExists(connection,
                ConfigPropertyConstants.VULNERABILITY_ID_ORG_CODE.getGroupName(),
                ConfigPropertyConstants.VULNERABILITY_ID_ORG_CODE.getPropertyName())
                || !configPropertyExists(connection,
                ConfigPropertyConstants.VULNERABILITY_ID_PROJECT_CODE.getGroupName(),
                ConfigPropertyConstants.VULNERABILITY_ID_PROJECT_CODE.getPropertyName())
                || !configPropertyExists(connection,
                ConfigPropertyConstants.VULNERABILITY_ID_TEMPLATE.getGroupName(),
                ConfigPropertyConstants.VULNERABILITY_ID_TEMPLATE.getPropertyName())
                || !configPropertyExists(connection,
                ConfigPropertyConstants.VULNERABILITY_ID_RESET_POLICY.getGroupName(),
                ConfigPropertyConstants.VULNERABILITY_ID_RESET_POLICY.getPropertyName())
                || !configPropertyExists(connection,
                ConfigPropertyConstants.VULNERABILITY_ID_SEQUENCE_PADDING.getGroupName(),
                ConfigPropertyConstants.VULNERABILITY_ID_SEQUENCE_PADDING.getPropertyName());
    }
}
