{
 "title": "Dependency-Track",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current Heap Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Total Published Events",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(alpine_events_published_total{instance=\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Total Published Notifications",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(alpine_notifications_published_total{instance=\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Java Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_info{instance=\"$instance\"}",
     "legendFormat": "{{vendor}} {{version}}"
    }
   ]
  },
  {
   "title": "Total Heap Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"$instance\"}",
     "legendFormat": "Process"
    },
    {
     "expr": "system_cpu_usage{instance=\"$instance\"}",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "Heap Usage"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "Non-Heap"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "Heap Size"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_daemon_threads{instance=\"$instance\"}",
     "legendFormat": "Daemon"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Event System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Events Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "increase(executor_completed_tasks_total{instance=\"$instance\", name=\"Alpine-EventService\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "increase(executor_completed_tasks_total{instance=\"$instance\", name=\"Alpine-SingleThreadedEventService\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Events Queued",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "executor_queued_tasks{instance=\"$instance\", name=\"Alpine-EventService\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "executor_queued_tasks{instance=\"$instance\", name=\"Alpine-SingleThreadedEventService\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Active Worker Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "executor_active_threads{instance=\"$instance\", name=\"Alpine-EventService\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "executor_active_threads{instance=\"$instance\", name=\"Alpine-SingleThreadedEventService\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Events Published",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "increase(alpine_events_published_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  { "title": "Notifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Notifications Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "increase(executor_completed_tasks_total{instance=\"$instance\", name=\"Alpine-NotificationService\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Notifications Queued",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "targets": [
    {
     "expr": "executor_queued_tasks{instance=\"$instance\", name=\"Alpine-NotificationService\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Active Worker Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "targets": [
    {
     "expr": "executor_active_threads{instance=\"$instance\", name=\"Alpine-NotificationService\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Notifications Published",
   "type": "timeseries",
   "description": "Notifications published by the system. Note that this includes ALL notifications, even those for which no alert was configured.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "increase(alpine_notifications_published_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{group}}"
    }
   ]
  }
 ]
}