/*
 * This file is part of Dependency-Track.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 * Copyright (c) OWASP Foundation. All Rights Reserved.
 */
package org.dependencytrack.upgrade.v500;

import alpine.common.logging.Logger;
import alpine.common.util.VersionComparator;
import alpine.persistence.AlpineQueryManager;
import alpine.server.upgrade.AbstractUpgradeItem;
import alpine.server.upgrade.UpgradeMetaProcessor;
import alpine.server.util.DbUtil;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Follow-up upgrade for schema version 5.0.0.
 * Creates a dedicated sequence table keyed by organization + project.
 */
public class v500_1Updater extends AbstractUpgradeItem {

    private static final Logger LOGGER = Logger.getLogger(v500_1Updater.class);

    @Override
    public String getSchemaVersion() {
        return "5.0.0";
    }

    @Override
    public boolean shouldUpgrade(final AlpineQueryManager qm, final Connection connection) {
        final UpgradeMetaProcessor upgradeMetaProcessor = new UpgradeMetaProcessor(connection);
        final boolean didThisUpgradeRun;
        final boolean didOldUpgradeVersionRun;
        try {
            didThisUpgradeRun = upgradeMetaProcessor.hasUpgradeRan(v500_1Updater.class);
            didOldUpgradeVersionRun = upgradeMetaProcessor.hasUpgradeRan(v500Updater.class);
        } catch (SQLException e) {
            throw new IllegalStateException("Failed to check whether %s ran before".formatted(v500Updater.class), e);
        }
        if (didThisUpgradeRun) {
            return false;
        }

        final VersionComparator currentVersion = upgradeMetaProcessor.getSchemaVersion();
        if (currentVersion == null) {
            return false;
        }

        final VersionComparator version = new VersionComparator(this.getSchemaVersion());
        return version.isNewerThan(currentVersion)
                || (version.equals(currentVersion) && didOldUpgradeVersionRun);
    }

    @Override
    public void executeUpgrade(final AlpineQueryManager qm, final Connection connection) throws Exception {
        createVulnerabilitySequenceV2Table(connection);
    }

    private void createVulnerabilitySequenceV2Table(final Connection connection) throws Exception {
        if (tableExists(connection, "VULNERABILITY_SEQUENCE_V2")) {
            LOGGER.debug("VULNERABILITY_SEQUENCE_V2 table already exists, skipping creation");
            return;
        }

        LOGGER.info("Creating VULNERABILITY_SEQUENCE_V2 table");
        final String dbProductName = connection.getMetaData().getDatabaseProductName().toLowerCase();
        final boolean isSqlServer = dbProductName.contains("sql server") || dbProductName.contains("microsoft");

        final String createTableSql = isSqlServer
                ? """
                CREATE TABLE "VULNERABILITY_SEQUENCE_V2" (
                    "ID" BIGINT IDENTITY(1,1) NOT NULL,
                    "ORG_CODE" VARCHAR(64) NOT NULL,
                    "PROJECT_KEY" VARCHAR(128) NOT NULL,
                    "CURRENT_SEQUENCE" BIGINT NOT NULL DEFAULT 0,
                    "LAST_RESET_DATE" DATETIME,
                    "RESET_POLICY" VARCHAR(32) NOT NULL,
                    "CREATED_AT" DATETIME DEFAULT GETDATE(),
                    PRIMARY KEY ("ID"),
                    CONSTRAINT "VULNSEQV2_ORG_PROJECT_UQ" UNIQUE ("ORG_CODE", "PROJECT_KEY")
                )
                """
                : """
                CREATE TABLE "VULNERABILITY_SEQUENCE_V2" (
                    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
                    "ORG_CODE" VARCHAR(64) NOT NULL,
                    "PROJECT_KEY" VARCHAR(128) NOT NULL,
                    "CURRENT_SEQUENCE" BIGINT NOT NULL DEFAULT 0,
                    "LAST_RESET_DATE" TIMESTAMP,
                    "RESET_POLICY" VARCHAR(32) NOT NULL,
                    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY ("ID"),
                    CONSTRAINT "VULNSEQV2_ORG_PROJECT_UQ" UNIQUE ("ORG_CODE", "PROJECT_KEY")
                )
                """;
        DbUtil.executeUpdate(connection, createTableSql);

        DbUtil.executeUpdate(connection, """
                CREATE INDEX "VULNSEQV2_ORG_IDX" ON "VULNERABILITY_SEQUENCE_V2" ("ORG_CODE")
                """);
        DbUtil.executeUpdate(connection, """
                CREATE INDEX "VULNSEQV2_PROJECT_IDX" ON "VULNERABILITY_SEQUENCE_V2" ("PROJECT_KEY")
                """);
    }

    private boolean tableExists(final Connection connection, final String tableName) throws SQLException {
        final DatabaseMetaData metaData = connection.getMetaData();
        try (ResultSet rs = metaData.getTables(null, null, tableName, new String[]{"TABLE"})) {
            return rs.next();
        }
    }
}
