/*
 * This file is part of Dependency-Track.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 * Copyright (c) OWASP Foundation. All Rights Reserved.
 */
package org.dependencytrack.upgrade.v500;

import alpine.common.logging.Logger;
import alpine.persistence.AlpineQueryManager;
import alpine.server.upgrade.AbstractUpgradeItem;
import alpine.server.util.DbUtil;
import org.dependencytrack.model.ConfigPropertyConstants;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 * Database upgrade for version 5.0.0
 *
 * Creates the VULNERABILITY_SEQUENCE table to track vulnerability ID sequences per project
 * and adds ConfigProperty entries for vulnerability ID customization.
 *
 * @since 5.0.0
 */
public class v500Updater extends AbstractUpgradeItem {

    private static final Logger LOGGER = Logger.getLogger(v500Updater.class);

    @Override
    public String getSchemaVersion() {
        return "5.0.0";
    }

    @Override
    public void executeUpgrade(AlpineQueryManager qm, Connection connection) throws Exception {
        LOGGER.info("Creating VULNERABILITY_SEQUENCE table");
        createVulnerabilitySequenceTable(connection);

        LOGGER.info("Adding vulnerability ID customization ConfigProperties");
        addConfigProperties(qm);
    }

    /**
     * Creates the VULNERABILITY_SEQUENCE table.
     *
     * This table tracks the sequence counter for each project to enable
     * unique vulnerability ID generation. It supports different reset policies
     * (YEARLY, MONTHLY, DAILY, NEVER) to reset the counter at specified intervals.
     *
     * @param connection the database connection
     * @throws Exception if table creation fails
     */
    private void createVulnerabilitySequenceTable(Connection connection) throws Exception {
        if (!tableExists(connection, "VULNERABILITY_SEQUENCE")) {
            final String dbProductName = connection.getMetaData().getDatabaseProductName().toLowerCase();
            final boolean isSqlServer = dbProductName.contains("sql server") || dbProductName.contains("microsoft");
            
            final String createTableSql = isSqlServer 
                ? """
                CREATE TABLE "VULNERABILITY_SEQUENCE" (
                    "ID" BIGINT IDENTITY(1,1) NOT NULL,
                    "PROJECT_ID" BIGINT NOT NULL,
                    "CURRENT_SEQUENCE" INT NOT NULL DEFAULT 0,
                    "LAST_RESET_DATE" DATETIME,
                    "RESET_POLICY" VARCHAR(32),
                    "CREATED_AT" DATETIME DEFAULT GETDATE(),
                    PRIMARY KEY ("ID"),
                    UNIQUE ("PROJECT_ID"),
                    FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECT" ("ID") ON DELETE CASCADE
                )
                """
                : """
                CREATE TABLE "VULNERABILITY_SEQUENCE" (
                    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
                    "PROJECT_ID" BIGINT NOT NULL,
                    "CURRENT_SEQUENCE" INT NOT NULL DEFAULT 0,
                    "LAST_RESET_DATE" TIMESTAMP,
                    "RESET_POLICY" VARCHAR(32),
                    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY ("ID"),
                    UNIQUE ("PROJECT_ID"),
                    FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECT" ("ID") ON DELETE CASCADE
                )
                """;
            
            DbUtil.executeUpdate(connection, createTableSql);
            LOGGER.debug("VULNERABILITY_SEQUENCE table created successfully for database: " + dbProductName);
        } else {
            LOGGER.debug("VULNERABILITY_SEQUENCE table already exists, skipping creation");
        }

        if (!indexExists(connection, "VULNERABILITY_SEQUENCE", "VULNERABILITY_SEQUENCE_PROJECT_IDX")) {
            DbUtil.executeUpdate(connection, """
                CREATE INDEX "VULNERABILITY_SEQUENCE_PROJECT_IDX"
                ON "VULNERABILITY_SEQUENCE" ("PROJECT_ID")
            """);

            LOGGER.debug("VULNERABILITY_SEQUENCE_PROJECT_IDX index created successfully");
        } else {
            LOGGER.debug("VULNERABILITY_SEQUENCE_PROJECT_IDX already exists, skipping creation");
        }
    }

    /**
     * Adds ConfigProperty entries for vulnerability ID customization.
     *
     * Creates the following configuration properties:
     * - vulnerability.id.org.code: Organization code (e.g., "TECAN")
     * - vulnerability.id.template: ID format template with variables
     * - vulnerability.id.reset.policy: Sequence reset policy (YEARLY, MONTHLY, DAILY, NEVER)
     * - vulnerability.id.sequence.padding: Number of digits for sequence padding
     *
     * @param qm the AlpineQueryManager
     */
    private void addConfigProperties(AlpineQueryManager qm) {
        createConfigPropertyIfAbsent(qm, ConfigPropertyConstants.VULNERABILITY_ID_ORG_CODE);
        createConfigPropertyIfAbsent(qm, ConfigPropertyConstants.VULNERABILITY_ID_TEMPLATE);
        createConfigPropertyIfAbsent(qm, ConfigPropertyConstants.VULNERABILITY_ID_RESET_POLICY);
        createConfigPropertyIfAbsent(qm, ConfigPropertyConstants.VULNERABILITY_ID_SEQUENCE_PADDING);
    }

    private void createConfigPropertyIfAbsent(final AlpineQueryManager qm, final ConfigPropertyConstants property) {
        if (qm.getConfigProperty(property.getGroupName(), property.getPropertyName()) != null) {
            LOGGER.debug("ConfigProperty already exists, skipping: " + property.name());
            return;
        }

        qm.createConfigProperty(
                property.getGroupName(),
                property.getPropertyName(),
                property.getDefaultPropertyValue(),
                property.getPropertyType(),
                property.getDescription()
        );
        LOGGER.debug("Created ConfigProperty: " + property.name());
    }

    private boolean tableExists(Connection connection, String tableName) throws SQLException {
        DatabaseMetaData metaData = connection.getMetaData();
        try (ResultSet rs = metaData.getTables(null, null, tableName, new String[] {"TABLE"})) {
            return rs.next();
        }
    }

    private boolean indexExists(Connection connection, String tableName, String indexName) throws SQLException {
        DatabaseMetaData metaData = connection.getMetaData();
        try (ResultSet rs = metaData.getIndexInfo(null, null, tableName, false, false)) {
            while (rs.next()) {
                String existingIndex = rs.getString("INDEX_NAME");
                if (existingIndex != null && existingIndex.equalsIgnoreCase(indexName)) {
                    return true;
                }
            }
        }
        return false;
    }
}
