<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<script type="text/javascript" src="<c:url value="/assets/jquery/jquery-3.2.1.min.js"/>"></script>
<script type="text/javascript" src="<c:url value="/assets/jquery/jquery.storageapi.min.js"/>"></script>
<script type="text/javascript" src="<c:url value="/assets/jquery/jquery.easypiechart.min.js"/>"></script>
<script type="text/javascript" src="<c:url value="/assets/jquery/typeahead.bundle.min.js"/>"></script>
<script type="text/javascript" src="<c:url value="/assets/bootstrap/js/bootstrap.min.js"/>"></script>
<script type="text/javascript" src="<c:url value="/assets/bootstrap-table/bootstrap-table.min.js"/>"></script>
<script type="text/javascript" src="<c:url value="/assets/bootstrap-table/extensions/flat-json/bootstrap-table-flat-json.min.js"/>"></script>
<script type="text/javascript" src="<c:url value="/assets/bootstrap-toggle/js/bootstrap-toggle.min.js"/>"></script>
<script type="text/javascript" src="<c:url value="/assets/bootstrap-tagsinput/bootstrap-tagsinput.min.js"/>"></script>
<script type="text/javascript" src="<c:url value="/assets/bootstrap-select/js/bootstrap-select.min.js"/>"></script>
<script type="text/javascript" src="<c:url value="/assets/d3/d3.v3.5.17.min.js"/>"></script>
<script type="text/javascript" src="<c:url value="/assets/d3/radar-chart.min.js"/>"></script>
<script type="text/javascript" src="<c:url value="/assets/d3/nv.d3.min.js"/>"></script>
<script type="text/javascript" src="<c:url value="/assets/js-xss/xss.min.js"/>"></script>
<script type="text/javascript" src="<c:url value="/assets/showdown/showdown.min.js"/>"></script>
<script type="text/javascript" src="<c:url value="/assets/showdown/showdown-xss-filter.js"/>"></script>
<script type="text/javascript" src="<c:url value="/assets/bind.min.js"/>"></script>
<script type="text/javascript" src="<c:url value="/assets/rest.js"/>"></script>
<script type="text/javascript" src="<c:url value="/assets/common.js"/>"></script>
