source 'https://rubygems.org'

gem 'jekyll', '3.7.4'

group :jekyll_plugins do
  gem 'jekyll-feed', '0.9.3'
  gem 'jekyll-seo-tag', '2.4.0'
  gem 'jekyll-sitemap', '1.2.0'
  gem 'jekyll-redirect-from'
  gem 'jekyll-mermaid', '~> 1.0'
end