name: Build CI

on:
  push:
    branches:
      - 'master'          # Default branch
      - 'feature-**'      # Feature branches
      - '[0-9]+.[0-9]+.x' # Release branches
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    branches:
      - 'master'          # Default branch
      - 'feature-**'      # Feature branches
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  workflow_dispatch:

permissions: { }

jobs:
  call-build:
    uses: ./.github/workflows/_meta-build.yaml
    with:
      app-version: "snapshot"
      publish-container: ${{ github.ref_name == 'master' || startsWith(github.ref_name, 'feature-') }}
      ref-name: ${{ github.ref_name }}
    permissions:
      security-events: write # Required to upload trivy's SARIF output
    secrets:
      registry-0-usr: ${{ secrets.HUB_USERNAME }}
      registry-0-psw: ${{ secrets.HUB_ACCESSS_TOKEN }}
