name: Build CI

on:
  push:
    branches:
      - '4.14.x'     # Release branch
      - 'feature-**' # Feature branches
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    branches:
      - '4.14.x'     # Release branch
      - 'feature-**' # Feature branches
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  workflow_dispatch:

permissions: { }

jobs:
  call-build:
    uses: ./.github/workflows/_meta-build.yaml
    with:
      app-version: "4-snapshot"
      publish-container: ${{ github.ref_name == '4.14.x' || startsWith(github.ref_name, 'feature-') }}
      ref-name: ${{ github.ref_name }}
    permissions:
      security-events: write # Required to upload trivy's SARIF output
    secrets:
      registry-0-usr: ${{ secrets.HUB_USERNAME }}
      registry-0-psw: ${{ secrets.HUB_ACCESSS_TOKEN }}
