name: Build CI

on:
  push:
    branches:
      - 'master'          # Default branch
      - '[0-9]+.[0-9]+.x' # Release branches
  pull_request:
    branches:
      - 'master'          # Default branch
  workflow_dispatch:

jobs:
  call-build:
    uses: ./.github/workflows/_meta-build.yaml
    with:
      app-version: "snapshot"
    secrets:
      registry-0-usr: ${{ secrets.HUB_USERNAME }}
      registry-0-psw: ${{ secrets.HUB_ACCESSS_TOKEN }}
