# This file is part of Dependency-Track.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) OWASP Foundation. All Rights Reserved.
name: Report PR Test Coverage

on:
  workflow_run:
    workflows:
    - Tests CI
    types:
    - completed

permissions: { }

jobs:
  publish:
    name: Report Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: |-
      github.event.workflow_run.event == 'pull_request'
        && github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Download PR workspace
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # tag=v8.0.1
      with:
        name: pr-workspace
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}
    - name: Ensure Git repository is initialized
      run: git init
    - name: Report Coverage to Codacy
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        COMMIT_SHA: ${{ github.event.workflow_run.head_sha }}
      run: |-
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
          --project-token "${CODACY_PROJECT_TOKEN}" \
          --commit-uuid "${COMMIT_SHA}" \
          --coverage-reports ./coverage-report/target/site/jacoco-aggregate/jacoco.xml \
          --language Java
