name: SAST scan

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '1.8.0'
    - name: Compile with Maven
      run: |
        mvn clean compile
    - name: Perform sast-scan
      uses: AppThreat/sast-scan-action@v1.0.0
      env:
        WORKSPACE: https://github.com/prabhu/dependency-track/blob/${{ env.GITHUB_SHA }}
      with:
        output: reports
      continue-on-error: true
    - name: Upload scan reports
      uses: actions/upload-artifact@v1.0.0
      with:
        name: sast-scan-reports
        path: reports
