name: SBOM Reachables
on:
  push:
    branches:
    - 'master'          # Default branch
    - '[0-9]+.[0-9]+.x' # Release branches
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  workflow_dispatch:

permissions: {}

jobs:
  cdxgen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # tag=v4.1.1
      - name: Set up JDK
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # tag=v3.13.0
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'
      - name: Run cdxgen
        run: |
          npm install -g @cyclonedx/cdxgen
          mvn clean compile -DskipTests -Dmaven.test.skip=true
          cdxgen -p -t java --profile research .
          mkdir -p bomresults
          cp bom.json *.slices.json bomresults
      - uses: actions/upload-artifact@v3
        with:
          name: bomresults
          path: bomresults
